services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: unless-stopped
    networks:
      default:
        ipv4_address: $UNBOUND_IP
    depends_on:
      - redis
    volumes:
      - ../data/unbound:/config
