services:
  # Lidarr - Music Management
  # Set url_base in lidarr settings if using PathPrefix
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - traefik_proxy
    volumes:
      - ../data/lidarr:/config
#      - $DATADIR:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.lidarr-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.lidarr-rtr-bypass.rule=Host(`lidarr.$PUBLIC_FQDN`) && Headers(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.lidarr-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.lidarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.lidarr-rtr.rule=Host(`lidarr.$PUBLIC_FQDN`)"
      - "traefik.http.routers.lidarr-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.lidarr-rtr-bypass.middlewares=chain-no-oauth@file"
      - "traefik.http.routers.lidarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.lidarr-rtr.service=lidarr-svc"
      - "traefik.http.routers.lidarr-rtr-bypass.service=lidarr-svc"
      - "traefik.http.services.lidarr-svc.loadbalancer.server.port=8686"