services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
