services:
  wordpress:
    image: wordpress:php8.2-fpm-alpine
    user: $PUID:$PGID
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - mariadb
    links:
      - mariadb
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../data/html:/var/www/html
      - ../data/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: mariadb
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
