version: "3.9"

# Declare Networks used by stack

networks:
  default:
    driver: bridge
  traefik_proxy:
    external: true

# Include Stack Services

include:
  - compose/mariadb.yml
  - compose/redis.yml
  - compose/wordpress.yml
  - compose/nginx.yml
  - compose/wpcli.yml